### ISSUE TITLE
Backend Rating Object does not open with many assigned records

### ISSUE THREAD

**Issue by ahaubold** [thucke/TYPO3.ext.th_rating#5]
When opening the backend rating object for pages an ErrorException is thrown:

`Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes)`

The reason therefor probably is the amount of results which is > 100.

Currently we are only able to get the rating results through a database query. E.g.

```
SELECT uid, pid, ratedobjectuid AS page, votes, currentrates
FROM `tx_thrating_domain_model_rating`
WHERE votes > 1 AND deleted=0 AND is_dummy_record=0 AND ratingobject=1
ORDER BY `votes` DESC
```
Our customer would like to access the results directly through the TYPO3 backend. Is there a way to do that?

**Comment by thucke** [comment]
Hi @ahaubold,
I'm trying to reproduce the error without having success.
Would you please give a short summary on your configuration:
* TYPO3 version
* PHP version
* MYSQL version
* Your PHP.INI
** memory_limit
** max_execution_time

Using SQL I've copied a row of tx_thrating_domain_model_rating up to the amount of 4096 instances. Having that amount of ratings I was able to open the concerned ratingobject in the backend.
My testing configuration is XAMPP (PHP 7.1.11, MariaDB 7.1.28, TYPO3 8.7.8).

**Comment by ahaubold** [comment]
Hello @thucke,

thank you for your investigation! 

Here is the summary of my configuration:

* TYPO3 7.6 LTS
* EXT:th_rating	1.5.1
* PHP 7.0.22 (FPM/FastCGI)
* MySQL: 5.7.20-0ubuntu0.16.04.1
* php.ini 
  * max_execution_time = 300
  * memory_limit = 512M

Currently are 15.700 assigned to the pages ratingobject (it's a huge website) in the tx_thrating_domain_model_rating table.

**Comment by thucke** [comment]
Hi @ahaubold ,
I admit that this amount could really reach the boundaries IRRE is designed for.
I'm afraid I have to think on a basically other solution (e.g. own BE module).
Will take some time.

**Comment by ahaubold** [comment]
Hello @thucke ,
I allready thought that it will be problematic - thanks for confirming this. Like you mentioned maybe another conceptual approach like a BE module for the statistics is necessary. For many users the stats are probably a relevant information and a BE module would have the advantage of better usability for this purpose.

**Comment by ahaubold** [comment]
Question is answered and issue can be marked as resolved.
