### ISSUE TITLE
Error for every plugin action

### ISSUE THREAD

**Issue by hugolaporte** [thucke/TYPO3.ext.th_rating#68]
Hi, I tried every plugin action configuration possible. 

For Ratinglinks I have this error :

> Return value of Thucke\ThRating\Domain\Model\Vote::getVoter() must be an instance of Thucke\ThRating\Domain\Model\Voter, null returned_

For Show, Polling, Mark, Index, I have this error (with the corresponding action) :

> Validation failed while trying to call Thucke\ThRating\Controller\VoteController->pollingAction().

I tried with the tt_content table (by default)
I also tried with tt_news table with that config 
```
plugin.tx_thrating {
	defaultObject {
		ratetable = tt_news
		ratefield = uid
		richSnippetFields {
			name = title
			description = bodytext
		}
	}
}
```

static_info_tables is installed
Static template is included (default setup)
TYPO3 9.5.11
PHP 7.3.10

Thank you

**Comment by hugolaporte** [comment]
Also have a BE error when I try to create a ratingstep name : 

> 2: SQL error: 'Incorrect integer value: '' for column 'sys_language_uid' at row 1' (tx_thrating_domain_model_stepname:NEW5de694098748a761312093)

Thank you Thomas

**Comment by thucke** [comment]
Hi @hugolaporte,

please apologize my late response - I'm currently very busy in my job.
Would it be possible to send me your complete template configuration?
Additionally it would be of interest for me which version of static_info_tables is installed.

Thank you
Thomas

**Comment by thucke** [comment]
Hmm , indeed - there seem to an issue with version 9. Investigating ...

**Comment by hugolaporte** [comment]
Hi Thomas,
Thanks for the answer. I tried a few things but I was not able to make the extension work so I built my own extension to rate my news. Sorry I could not help you more. Have a good day.

**Comment by wolfgang007** [comment]
Same problem. Already a solution?

**Comment by thucke** [comment]
@wolfgang007
Hi Wolfgang,
I thought it has been solved. Obviouslsy it hasn't or there's Apotheke cause.
Will need some time, though.

Greets
Thomas

**Comment by thucke** [comment]
> Same problem. Already a solution?

Hi @wolfgang007,
in which version of TYPO3 does the error appear in your environment?
This issue has been reported for TYPO3 9.5.
