### ISSUE TITLE
Can not create stepName

### ISSUE THREAD

**Issue by softstein** [thucke/TYPO3.ext.th_rating#82]
Creating a ratingstep (in t3 9.5.19) name throws a type error.
Class variables of the freshly instantiated class $stepnameObject are all NULL.

(1/1) TypeError
Argument 1 passed to Thucke\ThRating\Service\ExtensionHelperService::getStaticLanguageById() must be of the type integer, null given, called in /Users/Shared/Softstein/Composer_TYPO3_extDev/cms.softstein.com/typo3-9.x/development/web/public/typo3conf/ext/th_rating/Classes/Userfuncs/Tca.php on line 128

![type error](https://user-images.githubusercontent.com/6675234/86095598-72220a80-bab2-11ea-9971-1aea2e52b276.png)

**Comment by markushowald** [comment]
I have the same error here. TYPO3 10.4.6, th_rating 1.8.0

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to Thucke\ThRating\Service\ExtensionHelperService::getStaticLanguageById() must be of the type int, null given, called in /home/bfbcipi/public_html/bfbcipi.cyon.site/typo3/public/typo3conf/ext/th_rating/Classes/Userfuncs/Tca.php on line 125 | TypeError thrown in file /home/bfbcipi/public_html/bfbcipi.cyon.site/typo3/public/typo3conf/ext/th_rating/Classes/Service/ExtensionHelperService.php in line 691. Requested URL: https://bfbcipi.cyon.site/typo3/index.php?route=%%2Fajax%%2Frecord%%2Finline%%2Fcreate&token=--AnonymizedToken--`

**Comment by thucke** [comment]
@markushowald & @softstein 
I've uploaded version 1.8.1 implementing several fixes that possibly could also affect your issue.
Would you please give it a try?

It's also of my interest if you configured your site supporting the new site-feature.
Log into BE and check the left pane for "Site management" - "Sites". It's important having valid configuration here.

Thank you
Thomas

**Comment by markushowald** [comment]
@thucke 
Sorry for the late answer. I already removed the rating extension as the customer didn't want it in the end... so I just installed it again for testing — it works!

(Yes, the site-configuration is up and running)
