### ISSUE TITLE
AccessControlService can not detect logged in frontend user

### ISSUE THREAD

**Issue by lechenbauer** [thucke/TYPO3.ext.th_rating#93]
AccessControlService->hasLoggedInFrontendUser always returns false, resulting in an error: "Return value of Thucke\ThRating\Domain\Model\Vote::getVoter() must be an instance of Thucke\ThRating\Domain\Model\Voter, null returned". But $GLOBALS['TSFE']->fe_user is filled correctly.

Changing line 111 from $context = GeneralUtility::makeInstance(Context::class, array()); 
to $context = GeneralUtility::makeInstance(Context::class); solved the problem for me.
https://github.com/thucke/TYPO3.ext.th_rating/blob/develop/Classes/Service/AccessControlService.php#L111

Using TYPO3 10.4.13, PHP 7.3 and th_rating version 1.8.2

**Comment by thucke** [comment]
@lechenbauer - thank you very much

**Comment by lechenbauer** [comment]
@thucke - thanks for your super fast response and the new release! :)
